package com.yinian.autooa.model;

import com.yinian.autooa.common.Page;
import java.util.ArrayList;
import java.util.List;

public class DepartmentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table department
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table department
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table department
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table department
     *
     * @mbggenerated
     */
    protected Page page;

    /**
     *  构造查询条件,department
     */
    public DepartmentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     *  设置排序字段,department
     *
     * @param orderByClause 排序字段
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     *  获取排序字段,department
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     *  设置过滤重复数据,department
     *
     * @param distinct 是否过滤重复数据
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     *  是否过滤重复数据,department
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     *  获取当前的查询条件实例,department
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * ,department
     *
     * @param criteria 过滤条件实例
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * ,department
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     *  创建一个查询条件,department
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     *  内部构建查询条件对象,department
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *  清除查询条件,department
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * ,department
     *
     * @param page
     */
    public void setPage(Page page) {
        this.page=page;
    }

    /**
     * ,department
     */
    public Page getPage() {
        return page;
    }

    /**
     * null
     * GeneratedCriteria
     * 数据库表：department
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDepart_nameIsNull() {
            addCriterion("depart_name is null");
            return (Criteria) this;
        }

        public Criteria andDepart_nameIsNotNull() {
            addCriterion("depart_name is not null");
            return (Criteria) this;
        }

        public Criteria andDepart_nameEqualTo(String value) {
            addCriterion("depart_name =", value, "depart_name");
            return (Criteria) this;
        }

        public Criteria andDepart_nameNotEqualTo(String value) {
            addCriterion("depart_name <>", value, "depart_name");
            return (Criteria) this;
        }

        public Criteria andDepart_nameGreaterThan(String value) {
            addCriterion("depart_name >", value, "depart_name");
            return (Criteria) this;
        }

        public Criteria andDepart_nameGreaterThanOrEqualTo(String value) {
            addCriterion("depart_name >=", value, "depart_name");
            return (Criteria) this;
        }

        public Criteria andDepart_nameLessThan(String value) {
            addCriterion("depart_name <", value, "depart_name");
            return (Criteria) this;
        }

        public Criteria andDepart_nameLessThanOrEqualTo(String value) {
            addCriterion("depart_name <=", value, "depart_name");
            return (Criteria) this;
        }

        public Criteria andDepart_nameLike(String value) {
            addCriterion("depart_name like", value, "depart_name");
            return (Criteria) this;
        }

        public Criteria andDepart_nameNotLike(String value) {
            addCriterion("depart_name not like", value, "depart_name");
            return (Criteria) this;
        }

        public Criteria andDepart_nameIn(List<String> values) {
            addCriterion("depart_name in", values, "depart_name");
            return (Criteria) this;
        }

        public Criteria andDepart_nameNotIn(List<String> values) {
            addCriterion("depart_name not in", values, "depart_name");
            return (Criteria) this;
        }

        public Criteria andDepart_nameBetween(String value1, String value2) {
            addCriterion("depart_name between", value1, value2, "depart_name");
            return (Criteria) this;
        }

        public Criteria andDepart_nameNotBetween(String value1, String value2) {
            addCriterion("depart_name not between", value1, value2, "depart_name");
            return (Criteria) this;
        }

        public Criteria andDepart_descIsNull() {
            addCriterion("depart_desc is null");
            return (Criteria) this;
        }

        public Criteria andDepart_descIsNotNull() {
            addCriterion("depart_desc is not null");
            return (Criteria) this;
        }

        public Criteria andDepart_descEqualTo(String value) {
            addCriterion("depart_desc =", value, "depart_desc");
            return (Criteria) this;
        }

        public Criteria andDepart_descNotEqualTo(String value) {
            addCriterion("depart_desc <>", value, "depart_desc");
            return (Criteria) this;
        }

        public Criteria andDepart_descGreaterThan(String value) {
            addCriterion("depart_desc >", value, "depart_desc");
            return (Criteria) this;
        }

        public Criteria andDepart_descGreaterThanOrEqualTo(String value) {
            addCriterion("depart_desc >=", value, "depart_desc");
            return (Criteria) this;
        }

        public Criteria andDepart_descLessThan(String value) {
            addCriterion("depart_desc <", value, "depart_desc");
            return (Criteria) this;
        }

        public Criteria andDepart_descLessThanOrEqualTo(String value) {
            addCriterion("depart_desc <=", value, "depart_desc");
            return (Criteria) this;
        }

        public Criteria andDepart_descLike(String value) {
            addCriterion("depart_desc like", value, "depart_desc");
            return (Criteria) this;
        }

        public Criteria andDepart_descNotLike(String value) {
            addCriterion("depart_desc not like", value, "depart_desc");
            return (Criteria) this;
        }

        public Criteria andDepart_descIn(List<String> values) {
            addCriterion("depart_desc in", values, "depart_desc");
            return (Criteria) this;
        }

        public Criteria andDepart_descNotIn(List<String> values) {
            addCriterion("depart_desc not in", values, "depart_desc");
            return (Criteria) this;
        }

        public Criteria andDepart_descBetween(String value1, String value2) {
            addCriterion("depart_desc between", value1, value2, "depart_desc");
            return (Criteria) this;
        }

        public Criteria andDepart_descNotBetween(String value1, String value2) {
            addCriterion("depart_desc not between", value1, value2, "depart_desc");
            return (Criteria) this;
        }
    }

    /**
     * 类注释
     * Criteria
     * 数据库表：department
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * null
     * Criterion
     * 数据库表：department
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}