package com.yinian.autooa.model;

import com.yinian.autooa.common.Page;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FileExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table file
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table file
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table file
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table file
     *
     * @mbggenerated
     */
    protected Page page;

    /**
     *  构造查询条件,file
     */
    public FileExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     *  设置排序字段,file
     *
     * @param orderByClause 排序字段
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     *  获取排序字段,file
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     *  设置过滤重复数据,file
     *
     * @param distinct 是否过滤重复数据
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     *  是否过滤重复数据,file
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     *  获取当前的查询条件实例,file
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * ,file
     *
     * @param criteria 过滤条件实例
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * ,file
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     *  创建一个查询条件,file
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     *  内部构建查询条件对象,file
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *  清除查询条件,file
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * ,file
     *
     * @param page
     */
    public void setPage(Page page) {
        this.page=page;
    }

    /**
     * ,file
     */
    public Page getPage() {
        return page;
    }

    /**
     * null
     * GeneratedCriteria
     * 数据库表：file
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andSizeIsNull() {
            addCriterion("size is null");
            return (Criteria) this;
        }

        public Criteria andSizeIsNotNull() {
            addCriterion("size is not null");
            return (Criteria) this;
        }

        public Criteria andSizeEqualTo(Integer value) {
            addCriterion("size =", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeNotEqualTo(Integer value) {
            addCriterion("size <>", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeGreaterThan(Integer value) {
            addCriterion("size >", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeGreaterThanOrEqualTo(Integer value) {
            addCriterion("size >=", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeLessThan(Integer value) {
            addCriterion("size <", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeLessThanOrEqualTo(Integer value) {
            addCriterion("size <=", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeIn(List<Integer> values) {
            addCriterion("size in", values, "size");
            return (Criteria) this;
        }

        public Criteria andSizeNotIn(List<Integer> values) {
            addCriterion("size not in", values, "size");
            return (Criteria) this;
        }

        public Criteria andSizeBetween(Integer value1, Integer value2) {
            addCriterion("size between", value1, value2, "size");
            return (Criteria) this;
        }

        public Criteria andSizeNotBetween(Integer value1, Integer value2) {
            addCriterion("size not between", value1, value2, "size");
            return (Criteria) this;
        }

        public Criteria andLast_modify_datetimeIsNull() {
            addCriterion("last_modify_datetime is null");
            return (Criteria) this;
        }

        public Criteria andLast_modify_datetimeIsNotNull() {
            addCriterion("last_modify_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andLast_modify_datetimeEqualTo(Date value) {
            addCriterion("last_modify_datetime =", value, "last_modify_datetime");
            return (Criteria) this;
        }

        public Criteria andLast_modify_datetimeNotEqualTo(Date value) {
            addCriterion("last_modify_datetime <>", value, "last_modify_datetime");
            return (Criteria) this;
        }

        public Criteria andLast_modify_datetimeGreaterThan(Date value) {
            addCriterion("last_modify_datetime >", value, "last_modify_datetime");
            return (Criteria) this;
        }

        public Criteria andLast_modify_datetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_modify_datetime >=", value, "last_modify_datetime");
            return (Criteria) this;
        }

        public Criteria andLast_modify_datetimeLessThan(Date value) {
            addCriterion("last_modify_datetime <", value, "last_modify_datetime");
            return (Criteria) this;
        }

        public Criteria andLast_modify_datetimeLessThanOrEqualTo(Date value) {
            addCriterion("last_modify_datetime <=", value, "last_modify_datetime");
            return (Criteria) this;
        }

        public Criteria andLast_modify_datetimeIn(List<Date> values) {
            addCriterion("last_modify_datetime in", values, "last_modify_datetime");
            return (Criteria) this;
        }

        public Criteria andLast_modify_datetimeNotIn(List<Date> values) {
            addCriterion("last_modify_datetime not in", values, "last_modify_datetime");
            return (Criteria) this;
        }

        public Criteria andLast_modify_datetimeBetween(Date value1, Date value2) {
            addCriterion("last_modify_datetime between", value1, value2, "last_modify_datetime");
            return (Criteria) this;
        }

        public Criteria andLast_modify_datetimeNotBetween(Date value1, Date value2) {
            addCriterion("last_modify_datetime not between", value1, value2, "last_modify_datetime");
            return (Criteria) this;
        }

        public Criteria andLocationIsNull() {
            addCriterion("location is null");
            return (Criteria) this;
        }

        public Criteria andLocationIsNotNull() {
            addCriterion("location is not null");
            return (Criteria) this;
        }

        public Criteria andLocationEqualTo(String value) {
            addCriterion("location =", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotEqualTo(String value) {
            addCriterion("location <>", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationGreaterThan(String value) {
            addCriterion("location >", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationGreaterThanOrEqualTo(String value) {
            addCriterion("location >=", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLessThan(String value) {
            addCriterion("location <", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLessThanOrEqualTo(String value) {
            addCriterion("location <=", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLike(String value) {
            addCriterion("location like", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotLike(String value) {
            addCriterion("location not like", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationIn(List<String> values) {
            addCriterion("location in", values, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotIn(List<String> values) {
            addCriterion("location not in", values, "location");
            return (Criteria) this;
        }

        public Criteria andLocationBetween(String value1, String value2) {
            addCriterion("location between", value1, value2, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotBetween(String value1, String value2) {
            addCriterion("location not between", value1, value2, "location");
            return (Criteria) this;
        }

        public Criteria andParent_idIsNull() {
            addCriterion("parent_id is null");
            return (Criteria) this;
        }

        public Criteria andParent_idIsNotNull() {
            addCriterion("parent_id is not null");
            return (Criteria) this;
        }

        public Criteria andParent_idEqualTo(Integer value) {
            addCriterion("parent_id =", value, "parent_id");
            return (Criteria) this;
        }

        public Criteria andParent_idNotEqualTo(Integer value) {
            addCriterion("parent_id <>", value, "parent_id");
            return (Criteria) this;
        }

        public Criteria andParent_idGreaterThan(Integer value) {
            addCriterion("parent_id >", value, "parent_id");
            return (Criteria) this;
        }

        public Criteria andParent_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("parent_id >=", value, "parent_id");
            return (Criteria) this;
        }

        public Criteria andParent_idLessThan(Integer value) {
            addCriterion("parent_id <", value, "parent_id");
            return (Criteria) this;
        }

        public Criteria andParent_idLessThanOrEqualTo(Integer value) {
            addCriterion("parent_id <=", value, "parent_id");
            return (Criteria) this;
        }

        public Criteria andParent_idIn(List<Integer> values) {
            addCriterion("parent_id in", values, "parent_id");
            return (Criteria) this;
        }

        public Criteria andParent_idNotIn(List<Integer> values) {
            addCriterion("parent_id not in", values, "parent_id");
            return (Criteria) this;
        }

        public Criteria andParent_idBetween(Integer value1, Integer value2) {
            addCriterion("parent_id between", value1, value2, "parent_id");
            return (Criteria) this;
        }

        public Criteria andParent_idNotBetween(Integer value1, Integer value2) {
            addCriterion("parent_id not between", value1, value2, "parent_id");
            return (Criteria) this;
        }

        public Criteria andIs_folderIsNull() {
            addCriterion("is_folder is null");
            return (Criteria) this;
        }

        public Criteria andIs_folderIsNotNull() {
            addCriterion("is_folder is not null");
            return (Criteria) this;
        }

        public Criteria andIs_folderEqualTo(Integer value) {
            addCriterion("is_folder =", value, "is_folder");
            return (Criteria) this;
        }

        public Criteria andIs_folderNotEqualTo(Integer value) {
            addCriterion("is_folder <>", value, "is_folder");
            return (Criteria) this;
        }

        public Criteria andIs_folderGreaterThan(Integer value) {
            addCriterion("is_folder >", value, "is_folder");
            return (Criteria) this;
        }

        public Criteria andIs_folderGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_folder >=", value, "is_folder");
            return (Criteria) this;
        }

        public Criteria andIs_folderLessThan(Integer value) {
            addCriterion("is_folder <", value, "is_folder");
            return (Criteria) this;
        }

        public Criteria andIs_folderLessThanOrEqualTo(Integer value) {
            addCriterion("is_folder <=", value, "is_folder");
            return (Criteria) this;
        }

        public Criteria andIs_folderIn(List<Integer> values) {
            addCriterion("is_folder in", values, "is_folder");
            return (Criteria) this;
        }

        public Criteria andIs_folderNotIn(List<Integer> values) {
            addCriterion("is_folder not in", values, "is_folder");
            return (Criteria) this;
        }

        public Criteria andIs_folderBetween(Integer value1, Integer value2) {
            addCriterion("is_folder between", value1, value2, "is_folder");
            return (Criteria) this;
        }

        public Criteria andIs_folderNotBetween(Integer value1, Integer value2) {
            addCriterion("is_folder not between", value1, value2, "is_folder");
            return (Criteria) this;
        }

        public Criteria andShare_typeIsNull() {
            addCriterion("share_type is null");
            return (Criteria) this;
        }

        public Criteria andShare_typeIsNotNull() {
            addCriterion("share_type is not null");
            return (Criteria) this;
        }

        public Criteria andShare_typeEqualTo(Integer value) {
            addCriterion("share_type =", value, "share_type");
            return (Criteria) this;
        }

        public Criteria andShare_typeNotEqualTo(Integer value) {
            addCriterion("share_type <>", value, "share_type");
            return (Criteria) this;
        }

        public Criteria andShare_typeGreaterThan(Integer value) {
            addCriterion("share_type >", value, "share_type");
            return (Criteria) this;
        }

        public Criteria andShare_typeGreaterThanOrEqualTo(Integer value) {
            addCriterion("share_type >=", value, "share_type");
            return (Criteria) this;
        }

        public Criteria andShare_typeLessThan(Integer value) {
            addCriterion("share_type <", value, "share_type");
            return (Criteria) this;
        }

        public Criteria andShare_typeLessThanOrEqualTo(Integer value) {
            addCriterion("share_type <=", value, "share_type");
            return (Criteria) this;
        }

        public Criteria andShare_typeIn(List<Integer> values) {
            addCriterion("share_type in", values, "share_type");
            return (Criteria) this;
        }

        public Criteria andShare_typeNotIn(List<Integer> values) {
            addCriterion("share_type not in", values, "share_type");
            return (Criteria) this;
        }

        public Criteria andShare_typeBetween(Integer value1, Integer value2) {
            addCriterion("share_type between", value1, value2, "share_type");
            return (Criteria) this;
        }

        public Criteria andShare_typeNotBetween(Integer value1, Integer value2) {
            addCriterion("share_type not between", value1, value2, "share_type");
            return (Criteria) this;
        }

        public Criteria andUpload_usernameIsNull() {
            addCriterion("upload_username is null");
            return (Criteria) this;
        }

        public Criteria andUpload_usernameIsNotNull() {
            addCriterion("upload_username is not null");
            return (Criteria) this;
        }

        public Criteria andUpload_usernameEqualTo(String value) {
            addCriterion("upload_username =", value, "upload_username");
            return (Criteria) this;
        }

        public Criteria andUpload_usernameNotEqualTo(String value) {
            addCriterion("upload_username <>", value, "upload_username");
            return (Criteria) this;
        }

        public Criteria andUpload_usernameGreaterThan(String value) {
            addCriterion("upload_username >", value, "upload_username");
            return (Criteria) this;
        }

        public Criteria andUpload_usernameGreaterThanOrEqualTo(String value) {
            addCriterion("upload_username >=", value, "upload_username");
            return (Criteria) this;
        }

        public Criteria andUpload_usernameLessThan(String value) {
            addCriterion("upload_username <", value, "upload_username");
            return (Criteria) this;
        }

        public Criteria andUpload_usernameLessThanOrEqualTo(String value) {
            addCriterion("upload_username <=", value, "upload_username");
            return (Criteria) this;
        }

        public Criteria andUpload_usernameLike(String value) {
            addCriterion("upload_username like", value, "upload_username");
            return (Criteria) this;
        }

        public Criteria andUpload_usernameNotLike(String value) {
            addCriterion("upload_username not like", value, "upload_username");
            return (Criteria) this;
        }

        public Criteria andUpload_usernameIn(List<String> values) {
            addCriterion("upload_username in", values, "upload_username");
            return (Criteria) this;
        }

        public Criteria andUpload_usernameNotIn(List<String> values) {
            addCriterion("upload_username not in", values, "upload_username");
            return (Criteria) this;
        }

        public Criteria andUpload_usernameBetween(String value1, String value2) {
            addCriterion("upload_username between", value1, value2, "upload_username");
            return (Criteria) this;
        }

        public Criteria andUpload_usernameNotBetween(String value1, String value2) {
            addCriterion("upload_username not between", value1, value2, "upload_username");
            return (Criteria) this;
        }

        public Criteria andUpload_user_idIsNull() {
            addCriterion("upload_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUpload_user_idIsNotNull() {
            addCriterion("upload_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpload_user_idEqualTo(Integer value) {
            addCriterion("upload_user_id =", value, "upload_user_id");
            return (Criteria) this;
        }

        public Criteria andUpload_user_idNotEqualTo(Integer value) {
            addCriterion("upload_user_id <>", value, "upload_user_id");
            return (Criteria) this;
        }

        public Criteria andUpload_user_idGreaterThan(Integer value) {
            addCriterion("upload_user_id >", value, "upload_user_id");
            return (Criteria) this;
        }

        public Criteria andUpload_user_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("upload_user_id >=", value, "upload_user_id");
            return (Criteria) this;
        }

        public Criteria andUpload_user_idLessThan(Integer value) {
            addCriterion("upload_user_id <", value, "upload_user_id");
            return (Criteria) this;
        }

        public Criteria andUpload_user_idLessThanOrEqualTo(Integer value) {
            addCriterion("upload_user_id <=", value, "upload_user_id");
            return (Criteria) this;
        }

        public Criteria andUpload_user_idIn(List<Integer> values) {
            addCriterion("upload_user_id in", values, "upload_user_id");
            return (Criteria) this;
        }

        public Criteria andUpload_user_idNotIn(List<Integer> values) {
            addCriterion("upload_user_id not in", values, "upload_user_id");
            return (Criteria) this;
        }

        public Criteria andUpload_user_idBetween(Integer value1, Integer value2) {
            addCriterion("upload_user_id between", value1, value2, "upload_user_id");
            return (Criteria) this;
        }

        public Criteria andUpload_user_idNotBetween(Integer value1, Integer value2) {
            addCriterion("upload_user_id not between", value1, value2, "upload_user_id");
            return (Criteria) this;
        }
    }

    /**
     * 类注释
     * Criteria
     * 数据库表：file
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * null
     * Criterion
     * 数据库表：file
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}