package com.yinian.autooa.model;

import com.yinian.autooa.common.Page;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ScheduleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table schedule
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table schedule
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table schedule
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table schedule
     *
     * @mbggenerated
     */
    protected Page page;

    /**
     *  构造查询条件,schedule
     */
    public ScheduleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     *  设置排序字段,schedule
     *
     * @param orderByClause 排序字段
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     *  获取排序字段,schedule
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     *  设置过滤重复数据,schedule
     *
     * @param distinct 是否过滤重复数据
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     *  是否过滤重复数据,schedule
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     *  获取当前的查询条件实例,schedule
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * ,schedule
     *
     * @param criteria 过滤条件实例
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * ,schedule
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     *  创建一个查询条件,schedule
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     *  内部构建查询条件对象,schedule
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *  清除查询条件,schedule
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * ,schedule
     *
     * @param page
     */
    public void setPage(Page page) {
        this.page=page;
    }

    /**
     * ,schedule
     */
    public Page getPage() {
        return page;
    }

    /**
     * null
     * GeneratedCriteria
     * 数据库表：schedule
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andStart_datetimeIsNull() {
            addCriterion("start_datetime is null");
            return (Criteria) this;
        }

        public Criteria andStart_datetimeIsNotNull() {
            addCriterion("start_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andStart_datetimeEqualTo(Date value) {
            addCriterion("start_datetime =", value, "start_datetime");
            return (Criteria) this;
        }

        public Criteria andStart_datetimeNotEqualTo(Date value) {
            addCriterion("start_datetime <>", value, "start_datetime");
            return (Criteria) this;
        }

        public Criteria andStart_datetimeGreaterThan(Date value) {
            addCriterion("start_datetime >", value, "start_datetime");
            return (Criteria) this;
        }

        public Criteria andStart_datetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("start_datetime >=", value, "start_datetime");
            return (Criteria) this;
        }

        public Criteria andStart_datetimeLessThan(Date value) {
            addCriterion("start_datetime <", value, "start_datetime");
            return (Criteria) this;
        }

        public Criteria andStart_datetimeLessThanOrEqualTo(Date value) {
            addCriterion("start_datetime <=", value, "start_datetime");
            return (Criteria) this;
        }

        public Criteria andStart_datetimeIn(List<Date> values) {
            addCriterion("start_datetime in", values, "start_datetime");
            return (Criteria) this;
        }

        public Criteria andStart_datetimeNotIn(List<Date> values) {
            addCriterion("start_datetime not in", values, "start_datetime");
            return (Criteria) this;
        }

        public Criteria andStart_datetimeBetween(Date value1, Date value2) {
            addCriterion("start_datetime between", value1, value2, "start_datetime");
            return (Criteria) this;
        }

        public Criteria andStart_datetimeNotBetween(Date value1, Date value2) {
            addCriterion("start_datetime not between", value1, value2, "start_datetime");
            return (Criteria) this;
        }

        public Criteria andEnd_datetimeIsNull() {
            addCriterion("end_datetime is null");
            return (Criteria) this;
        }

        public Criteria andEnd_datetimeIsNotNull() {
            addCriterion("end_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andEnd_datetimeEqualTo(Date value) {
            addCriterion("end_datetime =", value, "end_datetime");
            return (Criteria) this;
        }

        public Criteria andEnd_datetimeNotEqualTo(Date value) {
            addCriterion("end_datetime <>", value, "end_datetime");
            return (Criteria) this;
        }

        public Criteria andEnd_datetimeGreaterThan(Date value) {
            addCriterion("end_datetime >", value, "end_datetime");
            return (Criteria) this;
        }

        public Criteria andEnd_datetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("end_datetime >=", value, "end_datetime");
            return (Criteria) this;
        }

        public Criteria andEnd_datetimeLessThan(Date value) {
            addCriterion("end_datetime <", value, "end_datetime");
            return (Criteria) this;
        }

        public Criteria andEnd_datetimeLessThanOrEqualTo(Date value) {
            addCriterion("end_datetime <=", value, "end_datetime");
            return (Criteria) this;
        }

        public Criteria andEnd_datetimeIn(List<Date> values) {
            addCriterion("end_datetime in", values, "end_datetime");
            return (Criteria) this;
        }

        public Criteria andEnd_datetimeNotIn(List<Date> values) {
            addCriterion("end_datetime not in", values, "end_datetime");
            return (Criteria) this;
        }

        public Criteria andEnd_datetimeBetween(Date value1, Date value2) {
            addCriterion("end_datetime between", value1, value2, "end_datetime");
            return (Criteria) this;
        }

        public Criteria andEnd_datetimeNotBetween(Date value1, Date value2) {
            addCriterion("end_datetime not between", value1, value2, "end_datetime");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andBelong_idIsNull() {
            addCriterion("belong_id is null");
            return (Criteria) this;
        }

        public Criteria andBelong_idIsNotNull() {
            addCriterion("belong_id is not null");
            return (Criteria) this;
        }

        public Criteria andBelong_idEqualTo(Integer value) {
            addCriterion("belong_id =", value, "belong_id");
            return (Criteria) this;
        }

        public Criteria andBelong_idNotEqualTo(Integer value) {
            addCriterion("belong_id <>", value, "belong_id");
            return (Criteria) this;
        }

        public Criteria andBelong_idGreaterThan(Integer value) {
            addCriterion("belong_id >", value, "belong_id");
            return (Criteria) this;
        }

        public Criteria andBelong_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("belong_id >=", value, "belong_id");
            return (Criteria) this;
        }

        public Criteria andBelong_idLessThan(Integer value) {
            addCriterion("belong_id <", value, "belong_id");
            return (Criteria) this;
        }

        public Criteria andBelong_idLessThanOrEqualTo(Integer value) {
            addCriterion("belong_id <=", value, "belong_id");
            return (Criteria) this;
        }

        public Criteria andBelong_idIn(List<Integer> values) {
            addCriterion("belong_id in", values, "belong_id");
            return (Criteria) this;
        }

        public Criteria andBelong_idNotIn(List<Integer> values) {
            addCriterion("belong_id not in", values, "belong_id");
            return (Criteria) this;
        }

        public Criteria andBelong_idBetween(Integer value1, Integer value2) {
            addCriterion("belong_id between", value1, value2, "belong_id");
            return (Criteria) this;
        }

        public Criteria andBelong_idNotBetween(Integer value1, Integer value2) {
            addCriterion("belong_id not between", value1, value2, "belong_id");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * 类注释
     * Criteria
     * 数据库表：schedule
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * null
     * Criterion
     * 数据库表：schedule
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}