package com.yinian.autooa.model;

import com.yinian.autooa.common.Page;
import java.util.ArrayList;
import java.util.List;

public class SysPermissionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_permission
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_permission
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_permission
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_permission
     *
     * @mbggenerated
     */
    protected Page page;

    /**
     *  构造查询条件,sys_permission
     */
    public SysPermissionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     *  设置排序字段,sys_permission
     *
     * @param orderByClause 排序字段
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     *  获取排序字段,sys_permission
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     *  设置过滤重复数据,sys_permission
     *
     * @param distinct 是否过滤重复数据
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     *  是否过滤重复数据,sys_permission
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     *  获取当前的查询条件实例,sys_permission
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * ,sys_permission
     *
     * @param criteria 过滤条件实例
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * ,sys_permission
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     *  创建一个查询条件,sys_permission
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     *  内部构建查询条件对象,sys_permission
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *  清除查询条件,sys_permission
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * ,sys_permission
     *
     * @param page
     */
    public void setPage(Page page) {
        this.page=page;
    }

    /**
     * ,sys_permission
     */
    public Page getPage() {
        return page;
    }

    /**
     * null
     * GeneratedCriteria
     * 数据库表：sys_permission
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPermission_codeIsNull() {
            addCriterion("permission_code is null");
            return (Criteria) this;
        }

        public Criteria andPermission_codeIsNotNull() {
            addCriterion("permission_code is not null");
            return (Criteria) this;
        }

        public Criteria andPermission_codeEqualTo(String value) {
            addCriterion("permission_code =", value, "permission_code");
            return (Criteria) this;
        }

        public Criteria andPermission_codeNotEqualTo(String value) {
            addCriterion("permission_code <>", value, "permission_code");
            return (Criteria) this;
        }

        public Criteria andPermission_codeGreaterThan(String value) {
            addCriterion("permission_code >", value, "permission_code");
            return (Criteria) this;
        }

        public Criteria andPermission_codeGreaterThanOrEqualTo(String value) {
            addCriterion("permission_code >=", value, "permission_code");
            return (Criteria) this;
        }

        public Criteria andPermission_codeLessThan(String value) {
            addCriterion("permission_code <", value, "permission_code");
            return (Criteria) this;
        }

        public Criteria andPermission_codeLessThanOrEqualTo(String value) {
            addCriterion("permission_code <=", value, "permission_code");
            return (Criteria) this;
        }

        public Criteria andPermission_codeLike(String value) {
            addCriterion("permission_code like", value, "permission_code");
            return (Criteria) this;
        }

        public Criteria andPermission_codeNotLike(String value) {
            addCriterion("permission_code not like", value, "permission_code");
            return (Criteria) this;
        }

        public Criteria andPermission_codeIn(List<String> values) {
            addCriterion("permission_code in", values, "permission_code");
            return (Criteria) this;
        }

        public Criteria andPermission_codeNotIn(List<String> values) {
            addCriterion("permission_code not in", values, "permission_code");
            return (Criteria) this;
        }

        public Criteria andPermission_codeBetween(String value1, String value2) {
            addCriterion("permission_code between", value1, value2, "permission_code");
            return (Criteria) this;
        }

        public Criteria andPermission_codeNotBetween(String value1, String value2) {
            addCriterion("permission_code not between", value1, value2, "permission_code");
            return (Criteria) this;
        }

        public Criteria andPermission_nameIsNull() {
            addCriterion("permission_name is null");
            return (Criteria) this;
        }

        public Criteria andPermission_nameIsNotNull() {
            addCriterion("permission_name is not null");
            return (Criteria) this;
        }

        public Criteria andPermission_nameEqualTo(String value) {
            addCriterion("permission_name =", value, "permission_name");
            return (Criteria) this;
        }

        public Criteria andPermission_nameNotEqualTo(String value) {
            addCriterion("permission_name <>", value, "permission_name");
            return (Criteria) this;
        }

        public Criteria andPermission_nameGreaterThan(String value) {
            addCriterion("permission_name >", value, "permission_name");
            return (Criteria) this;
        }

        public Criteria andPermission_nameGreaterThanOrEqualTo(String value) {
            addCriterion("permission_name >=", value, "permission_name");
            return (Criteria) this;
        }

        public Criteria andPermission_nameLessThan(String value) {
            addCriterion("permission_name <", value, "permission_name");
            return (Criteria) this;
        }

        public Criteria andPermission_nameLessThanOrEqualTo(String value) {
            addCriterion("permission_name <=", value, "permission_name");
            return (Criteria) this;
        }

        public Criteria andPermission_nameLike(String value) {
            addCriterion("permission_name like", value, "permission_name");
            return (Criteria) this;
        }

        public Criteria andPermission_nameNotLike(String value) {
            addCriterion("permission_name not like", value, "permission_name");
            return (Criteria) this;
        }

        public Criteria andPermission_nameIn(List<String> values) {
            addCriterion("permission_name in", values, "permission_name");
            return (Criteria) this;
        }

        public Criteria andPermission_nameNotIn(List<String> values) {
            addCriterion("permission_name not in", values, "permission_name");
            return (Criteria) this;
        }

        public Criteria andPermission_nameBetween(String value1, String value2) {
            addCriterion("permission_name between", value1, value2, "permission_name");
            return (Criteria) this;
        }

        public Criteria andPermission_nameNotBetween(String value1, String value2) {
            addCriterion("permission_name not between", value1, value2, "permission_name");
            return (Criteria) this;
        }
    }

    /**
     * 类注释
     * Criteria
     * 数据库表：sys_permission
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * null
     * Criterion
     * 数据库表：sys_permission
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}